/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "products.index": [],
    "products.store": [],
    "products.show": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.index": [],
    "categories.store": [],
    "categories.show": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "orders.index": [],
    "orders.store": [],
    "orders.show": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "orders.update": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "orders.destroy": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "tags.index": [],
    "tags.store": [],
    "tags.show": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "tags.update": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "tags.destroy": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "balances.index": [],
    "balances.store": [],
    "balances.show": [
        {
            "name": "balance",
            "required": true,
            "binding": "id"
        }
    ],
    "balances.update": [
        {
            "name": "balance",
            "required": true,
            "binding": "id"
        }
    ],
    "balances.destroy": [
        {
            "name": "balance",
            "required": true,
            "binding": "id"
        }
    ],
    "home": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "register": [],
    "register.store": [],
    "login": [],
    "login.store": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirm.store": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
